# !!!!!! 注意 !!!!!!
# 如果您是第一次在您的服务器上使用本插件，则请按需修改下面的配置!

# 检查更新，有效值为布尔值 (true 或 false) 。遇到无效值默认为 false 。
check_update: true

# 哪个世界将被用作游戏？安装了多世界插件的服务器可能需要此项。默认为 world 。有效值为字符串
gameworld: "world"

# 插件语言，默认为 zh_CN
language: "zh_CN"

# 游戏开始时间，以秒为单位，遇到无效值时默认使用 10 秒。
hunter_release_time: 60
# 游戏总时长，以分钟为单位，遇到无效值时默认 30 分钟。
game_time: 30
# 终止间 位置，格式 x y z ，遇到无效值时会发出警告，若游戏时玩家被淘汰但没有可用的终止间 位置，玩家将会在被淘汰的位置成为旁观者。
end_room_location: ""
# 每秒失去的硬币的数量，遇到无效值时默认使用 100 / 秒 。
coin_per_second: 100
# 开局拥有的游戏币总量。默认 180000 。
default_coin_amount: 180000
# 战斗球的冷却时间，默认 5 秒。
fightball_cooldown: 5
# 当逃走队员被捕时，当时拥有的B币该乘以几？默认值为 0.1 (即 1/10) 。
coin_multiplier_on_be_catched: 0.1
