# !!!!!! 注意 !!!!!!
# 如果您是第一次在您的服务器上使用本插件，则请按需修改下面的配置!

# 猎人释放时间，以秒为单位，遇到无效值时默认使用 60 秒。
hunter_release_time: 60
# 游戏总时长，以分钟为单位，遇到无效值时默认 30 分钟。
game_time: 30
# 终止间 位置，格式 x y z ，遇到无效值时会发出警告，若游戏时玩家被淘汰但没有可用的终止间 位置，玩家将会在被淘汰的位置成为旁观者。
end_room_location: "0 100 0"
# 每秒获得的B币的数量，遇到无效值时默认使用 100 / 秒 。
coin_per_second: 100
# 最少需要的猎人数量，遇到非数字或小于 0 的数字时默认为 1 。
least_hunter: 1
# 最少需要的逃走队员数量，遇到非数字或小于 0 的数字时默认为 3 。以下提供的值仅为推荐值。
least_runner: 3

####### ------------ 物品配置 ------------ #######
# 猎人暂停卡 物品类型，也就是把哪种物品看做 猎人暂停卡 处理。默认值: 金锭。
hpc_type: "minecraft:gold_ingot"
# 猎人暂停卡有效时间，单位: 秒，默认值: 3 秒。
hpc_time: 3

# 保命符 物品类型，也就是把哪种物品看做 保命符 处理。默认值: 铁锭。
sl_type: "minecraft:iron_ingot"

# 弃权镐可以挖掉的方块。遇到无效值时，默认为钻石块。
exiting_pickaxe_minable_block: "minecraft:diamond_block"