name: BattleForMoney
version: '${project.version}'
main: snw.bfm.BattleForMoney
api-version: 1.16
author: "SNWCreations"
description: '${project.description}'
website: https://github.com/SNWCreations/BattleForMoney
depend: [CommandAPI]
