name: RunForMoney
version: '${project.version}'
main: snw.rfm.RunForMoney
api-version: 1.16
author: "SNWCreations"
description: '${project.description}'
website: https://www.mcbbs.net/home.php?mod=space&uid=2190885

commands:
  start:
    description: "开始 '全员逃走中' 游戏。当提供 countDownTime 参数时，用提供的值作为猎人的释放时间。如果没有提供值或提供的值为负值，则使用配置文件提供的值。"
    usage: "/start [countDownTime]"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
  resume:
    description: "继续游戏进程。一般在所有游戏玩家掉线但都成功重连后使用。"
    usage: "/resume"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
  forcestop:
    description: "强制停止 '全员逃走中' 游戏。"
    usage: "/forcestop"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: fs
  hunter:
    description: "成为猎人。当 playername 参数存在时，则强制让 <playername> 玩家成为猎人。playername 可以为多个，例如 /hunter AA BB"
    usage: "/hunter [playername..]"
  runner:
    description: "成为逃走队员。当 playername 参数存在时，则强制让 <playername> 玩家成为逃走队员。playername 可以为多个，例如 /runner AA BB"
    usage: "/runner [playername..]"
  leaveteam:
    description: "离开所在队伍。当 playername 参数存在时，则强制让 <playername> 玩家离开其所在队伍。playername 可以为多个，例如 /leaveteam AA BB"
    usage: "/leaveteam [playername..]"
    aliases: lt
  endroom:
    description: "设置 x y z 为终止间位置。若 x y z 未提供，则设置执行者的位置为终止间位置。"
    usage: "/endroom [x] [y] [z]"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: erl
  newgroup:
    description: "新建名为 <name> 的猎人组。"
    usage: "/newgroup <name>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: ng
  removegroup:
    description: "移除 <name> 猎人组。"
    usage: "/removegroup <name>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: rg
  activategroup:
    description: "启用在 <name> 组内的所有猎人。"
    usage: "/activategroup <name>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: ag
  deactivategroup:
    description: "禁用在 <name> 组内的所有猎人。"
    usage: "/deactivategroup <name>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: dg
  joingroup:
    description: "成为 <name> 组的一具猎人。当 playername 参数存在时，将强制把 <playername> 玩家放入 <name> 组，但前提是该玩家需要是猎人。playername 可以为多个，例如 /jg AA BB"
    usage: "/joingroup <name> [playername..]"
    aliases: jg
  leavegroup:
    description: "从所在的组离开。当 playername 参数存在时，将强制使 <playername> 玩家离开其所在的组（不是队伍），但前提是该玩家需要是猎人。playername 可以为多个，例如 /lg AA BB"
    usage: "/leavegroup [playername..]"
    aliases: lg
  activatehunter:
    description: "启用猎人 <playername> 。当 x y z 提供时则将该猎人放置到提供的位置（适用于重复利用已禁用猎人的时候）。"
    usage: "/activatehunter <playername> [x] [y] [z]"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: ah
  deactivatehunter:
    description: "禁用猎人 <playername> 。"
    usage: "/deactivatehunter <playername>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: dh
  rfmitem:
    description: "获取本插件的一些游戏内道具。此命令属于配置工具，仅管理员可用。"
    usage: "/rfmitem <itemname>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: ri
  grouplist:
    description: "列出所有已创建的组。"
    usage: "/grouplist"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: gl
  teamlist:
    description: "列出两队伍中所有玩家的名字。"
    usage: "/teamlist"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: tl
  coinlist:
    description: "列出所有玩家的B币数量。"
    usage: "/coinlist"
    aliases: cl
  exportcoinlist:
    description: "导出现在的 B币榜 数据到一个文件。"
    usage: "/exportcoinlist"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: ecl
  rfmrespawn:
    description: "使 <playerName> 重新加入逃走中游戏。可以批量处理。"
    usage: "/rfmrespawn <playerName..>"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
  rfmsettingsquery:
    description: "查询现有的逃走中游戏配置。"
    usage: "/rfmsettingsquery"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
    aliases: rsq
  forcestart:
    description: "(开发者用的调试命令! 请勿使用!) 强制启动一次游戏。"
    usage: "/forcestart"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
  rfmtimer:
    description: "启用/禁用 剩余时间的显示。"
    usage: "/rfmtimer"
    permission-message: "§c只有管理员可以这么做！"
    permission: op
